// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Aether",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Aether",
            targets: ["AppModule"],
            bundleIdentifier: "com.rishiselarka.aether",
            teamIdentifier: "S8LD68K2KG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Assets.xcassets"],
            resources: [.process("Assets.xcassets")]
        )
    ],
    swiftLanguageModes: [.v6]
)